# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-05 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_status', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecord',
            name='end_time',
            field=models.DateTimeField(verbose_name='推出或结束时间'),
        ),
        migrations.AlterField(
            model_name='userrecord',
            name='start_time',
            field=models.DateTimeField(verbose_name='登录或开始时间'),
        ),
    ]
