# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-05 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_status', '0002_auto_20190505_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrecord',
            name='course',
        ),
        migrations.AddField(
            model_name='userrecord',
            name='cour_id',
            field=models.IntegerField(default=0, verbose_name='课程ID'),
        ),
    ]
