# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-05 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_status', '0003_auto_20190505_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecord',
            name='end_time',
            field=models.DateTimeField(default=None, verbose_name='推出或结束时间'),
        ),
        migrations.AlterField(
            model_name='userrecord',
            name='month',
            field=models.IntegerField(default=None, verbose_name='月份'),
        ),
        migrations.AlterField(
            model_name='userrecord',
            name='start_time',
            field=models.DateTimeField(default=None, verbose_name='登录或开始时间'),
        ),
    ]
