# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-06 10:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_status', '0005_auto_20190505_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrecord',
            old_name='cour_id',
            new_name='data_id',
        ),
    ]
