# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-06 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_status', '0007_auto_20190506_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecord',
            name='data_detail',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='点击信息详情'),
        ),
        migrations.AlterField(
            model_name='userrecord',
            name='data_id',
            field=models.IntegerField(default=None, null=True, verbose_name='点击信息ID'),
        ),
    ]
