# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-19 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_status', '0008_auto_20190506_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecord',
            name='end_time',
            field=models.DateTimeField(default=None, null=True, verbose_name='退出或结束时间'),
        ),
    ]
