# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-05 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190421_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoinfo',
            name='url',
            field=models.FileField(upload_to='vedio/', verbose_name='视频资源'),
        ),
    ]
